spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      username: root
#      password: pwd
#      timeout: 1
      database: admin
      uri: "mongodb://root:pwd@localhost:27017,localhost:27017/admin?serverSelectionTimeoutMS=1000&connectTimeoutMS=1000"

    mongo:
      repositories:
        enabled: true



productService:
  baseUrl: "http://localhost:8082"
  productServicePath: "/productInfoService/product/names/"
  timeout: 20

orderService:
  baseUrl: "http://localhost:8083"
  orderServicePath: "/orderSearchService/order/phone/"
  timeout: 5

logging:
  level:
    web: info
  config: classpath:logbackMDC.xml